### ISSUE TITLE
Information on the missing card-images?

### ISSUE THREAD

**Issue by appdevrs** [GwentCommunityDevelopers/gwent-data-release#10]
the latest card updates from 28th february delayed the release of my software.
the images of the new gold cards are the last missing part.

Any information on when they will be linked in the cards.json?

**Comment by jamieadkins95** [comment]
Apologies, I'm working on a way to better distribute the card data (i.e. it's own dedicated website), and I forgot to push the JSON with the new card images to GitHub. I've updated the [v0.9.22 branch](https://github.com/GwentCommunityDevelopers/gwent-data-release/tree/v0.9.22) just now.

If this happens again in the future, you can check if the new card images have been uploaded by changing the patch names in the image urls in the existing JSON.

e.g.
`https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv0.9.20%2F201772%2F20177200%2Fhigh.png?alt=media`

becomes

`https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv0.9.22%2F201772%2F20177200%2Fhigh.png?alt=media`

Only `v0.9.20` -> `v0.9.22` has changed.

**Comment by appdevrs** [comment]
awesome, thank you.
