### ISSUE TITLE
Brouver Hoog info in .json file does not correspond with info in game client

### ISSUE THREAD

**Issue by kachna96** [GwentCommunityDevelopers/gwent-data-release#16]
Expected json output: Order: Move a unit to the other row. If it's an enemy, damage it by 2; if it's an ally, boost it by 2.
Actual json output: Order: Move a unit to the other row. If it's an enemy, damage it by 2

I tried to create the json again via the python script but the result was the same.

**Comment by jamieadkins95** [comment]
Thanks for reporting, I've spotted the issue. Give me an hour to fix.

**Comment by jamieadkins95** [comment]
https://github.com/GwentCommunityDevelopers/gwent-data-release/releases/tag/v1.0.0.15-2
