### ISSUE TITLE
Updated card data

### ISSUE THREAD

**Issue by teddybee-r** [GwentCommunityDevelopers/gwent-data-release#17]
Someone reported errors in my database I don't know how many cards are affected but here is the updated stuff.
example card

> Ice troll
> Wrong: Every turn, on turn end, if you have less units than your opponent, boost self by 1.
> Correct: Every turn, on turn end, if you control fewer units on the battlefield than your opponent, boost self by 1.

this the source - the localization was last updated on 2018-10-30
"..\AppData\LocalLow\CDProjektRED\Gwent\Data\data_definitions"
[datadef.zip](https://github.com/GwentCommunityDevelopers/gwent-data-release/files/2546076/datadef.zip)

this is the updated cards.json
[cards.zip](https://github.com/GwentCommunityDevelopers/gwent-data-release/files/2546078/cards.zip)

**Comment by jamieadkins95** [comment]
Thanks, I've released an update using the new data_definitions.

Be sure to use the official release if you use our card images, we got some new images  from CDPR a few days ago that include the provision cost.

https://github.com/GwentCommunityDevelopers/gwent-data-release/releases/tag/v1.0.0.15-4
