### ISSUE TITLE
Regular updates

### ISSUE THREAD

**Issue by Soreine** [GwentCommunityDevelopers/gwent-data-release#21]
I was hoping to rely on this repository to automatically update my Chrome extension's data on every patch. It's been 5 days since the release of the December patch and `gwent-data-release` was not updated yet. I don't blame anyone on that since it takes effort to watch and maintain this. Rather, I'd like to know more about the process to update this repository, and see if I can help make it easier to maintain. What are the requirements and the limitations for updating this repo?

Here is my understanding of it so far:

1. Someone needs to watch for, or be alerted about updates coming in Gwent, and react to them.
2. This same person must have access to an updated installation of Gwent (so I guess a Windows PC with GOG installed), in order to grab the ZIP file at `Path\to\Gwent\GWENT_Data\StreamingAssets\data_definitions`
3. Now this person must run the script of `gwent-data` on this ZIP file. This can be done on a different computer (Unix for example), since this only require the ZIP file and python 3.
4. I guess that `gwent-data` outputs all the JSON found in this repo, so it's just a matter of committing the output to `gwent-data-release` at this point.

The only missing bit is card art PNGs. I see in `card.json` that the images are hosted on a Firebase project. I guess someone is hosting them for other's convenience. Where are the images taken from though? What's the cost of hosting these images on Firebase?

I'd be happy to do my best to help. Also, is there a general communication channel for GwentCommunityDevelopers ? :D

**Comment by Soreine** [comment]
Just want to say that I'm super thankful for all the resources you are maintaining. You guys seem to be updating this repository super regularly, which is awesome. I'm just curious if I can help push thing even further and have something close to a 24h delay for updates.

**Comment by jamieadkins95** [comment]
Apologies, I am away at the moment and have been since the December patch, so I haven't been available to update the repo.

Anyone is able to run the script for the data, but I am the bottleneck with the images. CDPR sends them to me (or I ask them) every update and then I have a script that generates the different sizes, puts them in the correct folder structure and then uploads them to firebase.

I only have my MacBook with me, so I can't grab the data_definitions file. If you could grab that and run the script to get the card data for the new patch, I'll email CDPR for the images, I can do the image upload step independently

**Comment by jamieadkins95** [comment]
If I am around on the day of the patch, I usually have the data ready on the same day, however sometimes it takes a couple of days for CDPR to get the images ready

**Comment by Soreine** [comment]
Thanks for the prompt response :) I see. Missing images are not an issue, for me at least since I can always have placeholders in the meantime. Oh wait... they include power and provisions :/ so I would need to work around that too.
I'll see if I have time later today, and try to submit the new card data here.

**Comment by teddybee-r** [comment]
[data_definitions.zip](https://github.com/GwentCommunityDevelopers/gwent-data-release/files/2660602/data_definitions.zip)

I only need the images because I host them for the Discord Gwent card bot.
On my website I layer my cards so I never have to update images for them.
Card Image >Card Border > Card Banner > Card Strength/Mulligan Values > Card Provision > Card Provision Values

**Comment by Soreine** [comment]
I've opened a [PR](https://github.com/GwentCommunityDevelopers/gwent-data-release/pull/22), but I have used the `data_definitions` from my own installation. I had not seen it was attached in your message @Ispyy :)

> On my website I layer my cards so I never have to update images for them.
Card Image >Card Border > Card Banner > Card Strength/Mulligan Values > Card Provision > Card Provision Values

That's the best approach indeed. Thanks :)
I'm still [developing my extension for Homecoming](https://soreine.github.io/hyper-gwent/). So far I based everything on the images hosted on Firebase, so I haven't done anything for strength and other details since they were embedded in the card arts hosted there. I've been shamelessly extracting the card info background, banners, and other assets from https://gwentgenerator.com But if you guys have a better source for these assets, I'd be glad to use it. I could even make a repo for them. It could be useful.
One last question, the card arts on Firebase have a transparent padding around them. What is it for? I'm doing some CSS magic for now to crop them, but it seems inaccurate. Should I be doing things differently?

**Comment by jamieadkins95** [comment]
Not sure why the cards have the transparent padding, that's just how CDPR give them to me

**Comment by jamieadkins95** [comment]
https://github.com/GwentCommunityDevelopers/gwent-data-release/releases/tag/v1.0.1.26

Appears CDPR removed the provision value from the card images, will ask them about that

**Comment by jamieadkins95** [comment]
Have updated `gwent-data` with the ability to supply your own card image urls.

Have added a note to this repo explaining what the cause of the delays are after a Gwent update.
