### ISSUE TITLE
Updated Images

### ISSUE THREAD

**Issue by teddybee-r** [GwentCommunityDevelopers/gwent-data-release#24]
Did you get the correct image data?
The current images are incorrect (based on a test build).

I received the new package and updated my stuff.
I don't know how you resize them but I do a photoshop batch job with save for web to reduce the file size to 30% (thumb/low) of what you upload.

**Comment by jamieadkins95** [comment]
CDPR sent me a new batch of images a couple of days ago. I'm on holiday at the moment with no access to a PC to do a data-release, but I did manage to ssh into a VM from my phone and kickoff the image upload process. Change the patch name in the image URLs to v1.1.1

**Comment by ARTLEXEY** [comment]
v1.1.1 Images without provision values. Sadly ;(

**Comment by jamieadkins95** [comment]
😑 Will email CDPR

**Comment by teddybee-r** [comment]
I have 1.1.1 with provisions.  
They were generated with provisions because I asked.
The download link is the same as the one without them but it has '-Provisions.zip' added.
Unless you already have it.

**Comment by jamieadkins95** [comment]
I have the leaders update with provisions, give me some time to upload, I'm still on holiday, will kick off the upload script from my phone.

I'm gonna work on a way of making the script more flexible to use other people's images. The patches dropping at awkward times (when I'm on holiday without a laptop for 2 weeks) is not ideal for me or you guys

**Comment by jamieadkins95** [comment]
https://github.com/GwentCommunityDevelopers/gwent-data-release/releases/tag/v1.2.1

**Comment by jamieadkins95** [comment]
`gwent-data` now lets you supply your own image urls with placeholders. See the [updated README](https://github.com/GwentCommunityDevelopers/gwent-data/blob/eb08028dfa4938792d6ce7d536177eebd94ad000/README.md)
