### ISSUE TITLE
Some cards is missing

### ISSUE THREAD

**Issue by ARTLEXEY** [GwentCommunityDevelopers/gwent-data-release#25]
Some cards is missing. 
For example, Duda: Companion. In game id = 112403.
He just haven't link on the firebasestorage.
https://pastebin.com/F5za3qqR
Can you fix this?

**Comment by jamieadkins95** [comment]
CDPR provides us with the card images, but they don't give us images for token cards. This is why Duda: Companion and other token cards don't have an image.

You'll have to use a placeholder image instead, sorry.
