### ISSUE TITLE
"low" art size is the same than "thumbnail"

### ISSUE THREAD

**Issue by Soreine** [GwentCommunityDevelopers/gwent-data-release#26]
Hi @jamieadkins95 
I just noticed after using the latest data that the `low` artwork for the cards are now the same size than `thumbnail`. `low` used to be in-between `thumbnail` and `medium`, and was a perfect fit for my use case. Maybe something has gone wrong in the last update ?

Exemple for Ciri
[thumbnail](https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv2.0.0%2F112101%2F11210100%2Fthumbnail.png?alt=media)
[low](https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv2.0.0%2F112101%2F11210100%2Flow.png?alt=media)
[medium](https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv2.0.0%2F112101%2F11210100%2Fmedium.png?alt=media)

**Comment by jamieadkins95** [comment]
I've possibly made a copy/paste error. I've got a new script that generates the different card sizes, all the images are generated in parallel now and it takes about 5 seconds to make all the images, compared to the 25mins it took before.

I'll take a look

**Comment by jamieadkins95** [comment]
I kicked off the script again to regenerate the images. Ciri looks the correct resolution now :)

**Comment by Soreine** [comment]
Thank you for your awesomeness :)
