### ISSUE TITLE
Midwinter update

### ISSUE THREAD

**Issue by ghost** [GwentCommunityDevelopers/gwent-data-release#6]
Will the new cards and changes brought by the Midwinter update be included in a future release?

**Comment by jamieadkins95** [comment]
Apologies, we have a JSON for the Midwinter update. Submitting a PR now.

**Comment by jamieadkins95** [comment]
Don't have the keywords JSON on me at the moment so I can't submit the PR, but if you just need the cards JSON then you can find it on the [release/midwinter branch](https://github.com/GwentCommunityDevelopers/gwent-data-release/tree/release/midwinter).

**Comment by ghost** [comment]
Thank you very much for the quick reply. I just need the cards, thank you for the link!

**Comment by jamieadkins95** [comment]
Just a warning, CDPR significantly changed how they store Card Data in the Midwinter update. We haven't worked out how they do Categories yet, so those are missing in the latest JSON.

**Comment by jamieadkins95** [comment]
@vlacorte update has been pushed to master. An issue with the french and italian translations was resolved.
