### ISSUE TITLE
JSON for patch 0.9.20.6.390

### ISSUE THREAD

**Issue by victorlacorte** [GwentCommunityDevelopers/gwent-data-release#8]
The patch was released yesterday and since it changed the game quite a bit will it be included as a JSON release?

**Comment by jamieadkins95** [comment]
Hey,

We are waiting on official card images from CDPR, but the updated card data with old card images is currently on the [v0.9.20](https://github.com/GwentCommunityDevelopers/gwent-data-release/tree/v0.9.20) branch.

**Comment by victorlacorte** [comment]
Thank you!

**Comment by jamieadkins95** [comment]
@victorlacorte 
Card json with latest images is on master 👍

**Comment by victorlacorte** [comment]
@jamieadkins95 Thank you very much for your work!
